-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 17:22:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_contagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_contagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_contagem` DEFAULT CHARACTER SET utf8 ;
USE `bd_contagem` ;

-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_tamanhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_tamanhos` (
  `id_tamanho` INT NOT NULL,
  `nome_tamanho` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_tamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_cores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_cores` (
  `id_cor` INT NOT NULL,
  `nome_cor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_produtos` (
  `id_produto` INT NOT NULL,
  `cod_prod` INT(4) NOT NULL,
  `id_prodpai` INT NULL,
  `nome_prod` VARCHAR(50) NULL,
  `imagem` VARCHAR(150) NOT NULL,
  `tb_tamanhos_id_tamanho` INT NOT NULL,
  `tb_cores_id_cor` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produtos_UNIQUE` (`id_produto` ASC),
  INDEX `fk_tb_produtos_tb_tamanhos1_idx` (`tb_tamanhos_id_tamanho` ASC),
  INDEX `fk_tb_produtos_tb_cores1_idx` (`tb_cores_id_cor` ASC),
  CONSTRAINT `fk_tb_produtos_tb_tamanhos1`
    FOREIGN KEY (`tb_tamanhos_id_tamanho`)
    REFERENCES `bd_contagem`.`tb_tamanhos` (`id_tamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_cores1`
    FOREIGN KEY (`tb_cores_id_cor`)
    REFERENCES `bd_contagem`.`tb_cores` (`id_cor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_tipo_usuarios` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `desc_tipo_UNIQUE` (`desc_tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(50) NOT NULL,
  `email_usuario` VARCHAR(50) NOT NULL,
  `senha_usuario` VARCHAR(250) NOT NULL,
  `tb_tipo_usuarios_id_tipo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC),
  INDEX `fk_tb_usuarios_tb_tipo_usuarios_idx` (`tb_tipo_usuarios_id_tipo` ASC),
  CONSTRAINT `fk_tb_usuarios_tb_tipo_usuarios`
    FOREIGN KEY (`tb_tipo_usuarios_id_tipo`)
    REFERENCES `bd_contagem`.`tb_tipo_usuarios` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_status_contagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_status_contagem` (
  `id_status` INT NOT NULL,
  `desc_status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `desc_status_UNIQUE` (`desc_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_contagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_contagens` (
  `id_contagem` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `tb_usuarios_id_usuario` INT NOT NULL,
  `tb_produtos_id_produto` INT NOT NULL,
  `tb_status_contagem_id_status` INT NOT NULL,
  PRIMARY KEY (`id_contagem`),
  INDEX `fk_tb_contagens_tb_usuarios1_idx` (`tb_usuarios_id_usuario` ASC),
  INDEX `fk_tb_contagens_tb_produtos1_idx` (`tb_produtos_id_produto` ASC),
  INDEX `fk_tb_contagens_tb_status_contagem1_idx` (`tb_status_contagem_id_status` ASC),
  CONSTRAINT `fk_tb_contagens_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id_usuario`)
    REFERENCES `bd_contagem`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_contagens_tb_produtos1`
    FOREIGN KEY (`tb_produtos_id_produto`)
    REFERENCES `bd_contagem`.`tb_produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_contagens_tb_status_contagem1`
    FOREIGN KEY (`tb_status_contagem_id_status`)
    REFERENCES `bd_contagem`.`tb_status_contagem` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_contsub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_contsub` (
  `id_contsub` INT NOT NULL AUTO_INCREMENT,
  `tb_produtos_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_contsub`),
  INDEX `fk_tb_contsub_tb_produtos1_idx` (`tb_produtos_id_produto` ASC),
  CONSTRAINT `fk_tb_contsub_tb_produtos1`
    FOREIGN KEY (`tb_produtos_id_produto`)
    REFERENCES `bd_contagem`.`tb_produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_contagem`.`tb_contagem_contsub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contagem`.`tb_contagem_contsub` (
  `id_contagem_contsub` INT NOT NULL,
  `tb_contagens_id_contagem` INT NOT NULL,
  `tb_contsub_id_contsub` INT NOT NULL,
  PRIMARY KEY (`id_contagem_contsub`),
  INDEX `fk_tb_contagem_contsub_tb_contagens1_idx` (`tb_contagens_id_contagem` ASC),
  INDEX `fk_tb_contagem_contsub_tb_contsub1_idx` (`tb_contsub_id_contsub` ASC),
  CONSTRAINT `fk_tb_contagem_contsub_tb_contagens1`
    FOREIGN KEY (`tb_contagens_id_contagem`)
    REFERENCES `bd_contagem`.`tb_contagens` (`id_contagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_contagem_contsub_tb_contsub1`
    FOREIGN KEY (`tb_contsub_id_contsub`)
    REFERENCES `bd_contagem`.`tb_contsub` (`id_contsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
